[project]
name = "gestao-cpm-agno"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=2.3.2",
    "fastapi>=0.121.3",
    "openai>=2.8.1",
    "sqlalchemy>=2.0.44",
    "uvicorn>=0.38.0",
]
